
[functions.test-kis-token]
enabled = true
verify_jwt = true
import_map = "./functions/test-kis-token/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/test-kis-token/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/test-kis-token/*.html" ]

[functions.test-kis-price]
enabled = true
verify_jwt = true
import_map = "./functions/test-kis-price/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/test-kis-price/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/test-kis-price/*.html" ]

[functions.test-kis-top-volume]
enabled = true
verify_jwt = true
import_map = "./functions/test-kis-top-volume/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/test-kis-top-volume/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/test-kis-top-volume/*.html" ]

[functions.test-kis-top-change-rate]
enabled = true
verify_jwt = true
import_map = "./functions/test-kis-top-change-rate/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/test-kis-top-change-rate/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/test-kis-top-change-rate/*.html" ]

[functions.run-stock-scan]
enabled = true
verify_jwt = true
import_map = "./functions/run-stock-scan/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/run-stock-scan/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/run-stock-scan/*.html" ]

[functions.fetch-stock-history]
enabled = true
verify_jwt = true
import_map = "./functions/fetch-stock-history/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fetch-stock-history/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fetch-stock-history/*.html" ]

[functions.fetch-global-market-signal]
enabled = true
verify_jwt = true
import_map = "./functions/fetch-global-market-signal/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fetch-global-market-signal/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fetch-global-market-signal/*.html" ]

[functions.create-ebook-order]
enabled = true
verify_jwt = true
import_map = "./functions/create-ebook-order/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-ebook-order/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-ebook-order/*.html" ]

[functions.confirm-ebook-payment]
enabled = true
verify_jwt = true
import_map = "./functions/confirm-ebook-payment/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/confirm-ebook-payment/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/confirm-ebook-payment/*.html" ]

[functions.download-ebook]
enabled = true
verify_jwt = true
import_map = "./functions/download-ebook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/download-ebook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/download-ebook/*.html" ]
